# Generated by Django 3.2.7 on 2021-09-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opuser',
            name='password',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
