# Generated by Django 3.2.7 on 2021-09-04 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_teamtask_usertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtask',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usertask',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.opuser'),
        ),
    ]
