# Generated by Django 3.2.7 on 2021-09-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210904_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='opuser',
            name='attention',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opuser',
            name='docs_count',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opuser',
            name='immersion',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opuser',
            name='stress_tolerance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
